var cloudinary = require('cloudinary');

cloudinary.config({
  cloud_name: process.env.CLOUD_NAME,
  api_key: process.env.CLOUDINARY_KEY,
  api_secret: process.env.CLOUDINARY_SECRET
});

// File upload
cloudinary.uploader.upload('pizza.jpg',{tags:'basic_sample'},function(err,image){
  console.log();
  console.log("** File Upload");
  if (err){ console.warn(err);}
  console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
  console.log("* "+image.public_id);
  console.log("* "+image.url);
  waitForAllUploads("pizza",err,image);
});
